# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df2e0facfdeef50ef9ba014aff91763840091d0fd616a5c8db51e198fb3b20f777bb444ace30e16b0c83280b9cdbc4052dad15d6e460b115911c975557d1f721

test:
  secret_key_base: a043d06c5a3b2df2b6641c7dc9770c36a124a5287701d566521352f543cad9fd44bdd6ac44a9fe7969e6865d7d877a4db38dcd144417a315846a9951933ff249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
