Vehicule.create!([
  {name: "28 AND 29 PASSENGER MINI COACHES", vehicule_type: "shuttle", info: "Smaller economical options to move your group!!\r\nCD Player\r\nDVD Player\r\nNavigational System\r\nClimate Controlled\r\nPerfect for Corporate Groups, Weddings and any other event!", tv: false, bathroom: false, dvd_player: true, cd_player: true, am_fm_radio: false, cooler: false, nav_system: true, sound_system: false, wheelchair: false, bluetooth: false, leather: false, display_image: "vehicule1.jpg", seats: "28-29"},
  {name: "5 PASSENGER MKT LINCOLN TOWNCAR", vehicule_type: "sedan", info: "Executive Style Towncar perfect for any occasion\r\nBuilt in Cooler\r\nBlue Tooth Capability\r\nLimousine Style floor lighting\r\nHeated and Cooled Seats\r\nClimate Controlled\r\nCD Player AM/FM Radio\r\nTravel in Luxury and Style", tv: false, bathroom: false, dvd_player: false, cd_player: true, am_fm_radio: true, cooler: true, nav_system: false, sound_system: false, wheelchair: false, bluetooth: true, leather: false, display_image: "vehicule2.jpg", seats: "5"},
  {name: "6 Passenger Infinity QX SUV", vehicule_type: "sedan", info: "Travel in Style in our Luxurious 6 passenger SUV\r\nClimate Controlled\r\nState of the Art CD & DVD Player\r\nLeather Interior", tv: false, bathroom: false, dvd_player: true, cd_player: true, am_fm_radio: false, cooler: false, nav_system: false, sound_system: false, wheelchair: false, bluetooth: false, leather: false, display_image: "sedan_inf_qx.jpg", seats: "6"},
  {name: "2015 MERCEDES S550", vehicule_type: "sedan", info: "The ultimate in Luxury!!\r\n- CD Player\r\n- Climate Control\r\n- Roomy Interior\r\n- Spacious trunk for Luggage, golf bags etc.\r\n- Premium Sound System\r\n- Navigation system", tv: false, bathroom: false, dvd_player: false, cd_player: true, am_fm_radio: false, cooler: false, nav_system: true, sound_system: true, wheelchair: false, bluetooth: false, leather: false, display_image: "sedan_mercedes_s550.jpg", seats: "5"},
  {name: "EXCURSION ICON LIMOUSINE", vehicule_type: "limousine", info: "Featuring the 140\" Excursion Icon Limousine, a top-of-the-line limousine for your very special occasion. Our ICON is equipped 4 Flat Screens TV's  a Rosewood Bar,  a DVD, CD, AM/FM/AUX  stereo with surround and premium sound system and touch screen controls.  Our fiber optic bar featuring 6 different colors along with a mirrored ceiling with Twinkle Lights makes this an exceptional ride for your special day.", tv: true, bathroom: false, dvd_player: true, cd_player: true, am_fm_radio: true, cooler: false, nav_system: false, sound_system: true, wheelchair: false, bluetooth: false, leather: false, display_image: "limo.jpg", seats: nil},
  {name: "12 Passenger Vans/Airport Shuttles", vehicule_type: "shuttle", info: "Economical Transportation Option\r\nAirport Transfers\r\nSafe, Reliable Transportation\r\nClimate Controlled\r\nCD Players\r\nGreat for Small Groups", tv: false, bathroom: false, dvd_player: false, cd_player: true, am_fm_radio: false, cooler: false, nav_system: false, sound_system: false, wheelchair: false, bluetooth: false, leather: false, display_image: "12_passenger_van.jpg", seats: "12"},
  {name: "HANDICAP ACCESSIBLE VEHICLES", vehicule_type: "shuttle", info: "Large Fleet of Handicap/Wheelchair Accessible Vehicles\r\nClimate Controlled\r\nADA Compliant\r\nSafe, Reliable Accessible Vehicles\r\nFully Trained Drivers\r\nCD Players\r\nGreat for Adult Day Care Programs, Day Habilitation Programs, Doctor visits, or Nursing Homes!!", tv: false, bathroom: false, dvd_player: false, cd_player: true, am_fm_radio: false, cooler: false, nav_system: false, sound_system: false, wheelchair: true, bluetooth: false, leather: false, display_image: "handicap_accessible.jpg", seats: nil},
  {name: "47-55 PASSENGER COACHES", vehicule_type: "bus", info: "Economical & Safe Transportation\r\nClimate Controlled\r\nPerfect for Travel both Local and Nationwide\r\nCD and DVD Players\r\nState of the Art Surround Sound System\r\nFlat Screen Monitors\r\nBathrooms\r\nUnderneath Bus Luggage Storage\r\nGreat for Large Groups", tv: true, bathroom: true, dvd_player: true, cd_player: true, am_fm_radio: false, cooler: false, nav_system: false, sound_system: true, wheelchair: false, bluetooth: false, leather: false, display_image: "47_55_passenger_coaches.jpg", seats: "47-55"},
  {name: "55 PASSENGER COACH", vehicule_type: "bus", info: "Full size Motor Coach\r\nClimate Controlled\r\nCD and DVD Players\r\nState of the Art Surround System and Flat Screen Monitors\r\nBathroom\r\nReliable and Economical Travel Option", tv: true, bathroom: true, dvd_player: true, cd_player: true, am_fm_radio: false, cooler: false, nav_system: false, sound_system: true, wheelchair: false, bluetooth: false, leather: false, display_image: "55_passenger_coaches.jpg", seats: "55"},
  {name: "24 PASSENGER EXECUTIVE MINI-COACH", vehicule_type: "bus", info: "Ride in Style in our 24 passenger Executive Mini-Coach\r\nPerfect for Corporate Groups, Weddings, or any special occasion!!\r\nIce Cold AC\r\nLeather Interior with two tables\r\nFully loaded and ready to roll!!\r\nCD Player\r\nDVD Player with State of the Art Sound System and  Flat Screen Monitors", tv: true, bathroom: false, dvd_player: true, cd_player: true, am_fm_radio: false, cooler: false, nav_system: false, sound_system: true, wheelchair: false, bluetooth: false, leather: false, display_image: "24_passenger_mini_coach.jpg", seats: "24"},
  {name: "TROLLEY", vehicule_type: "bus", info: "Introducing the 32 passenger trolley from Urban Express. This bus will bring a lot of fun to your next special event.\r\nIdeal for any event. Call us today!\r\n\r\nOld fashioned elegance with new fashioned comfort.\r\nIce cold AC\r\nPanoramic Windows\r\n32 passenger\r\nWheelchair accessible\r\nCD Player", tv: false, bathroom: false, dvd_player: false, cd_player: true, am_fm_radio: false, cooler: false, nav_system: false, sound_system: false, wheelchair: true, bluetooth: false, leather: false, display_image: "trolley.jpg", seats: "32"}
])
